### ISSUE TITLE
getc in raw-mode

### ISSUE THREAD

**Issue by kuerbis** [krunen/term-termios#2]
Hi,

since there is no answer to this question: http://stackoverflow.com/questions/31958891/perl6-getc-in-raw-mode, maybe this is  a bug.

**Comment by krunen** [comment]
As the later answer says, you must use read(1) instead of getc(), which uses the built-in utf8 parser. This parser will wait for a possible combining unicode character, so it's useless for terminals. But then you must parse your own utf8 bytes.

I am working on a better solution that will work on windows and unixes.
